"""
RefreshToken ORM model.

Defines the server-side refresh token store for session management and revocation.
Every active authenticated session has a corresponding refresh token record that
enables token rotation, selective revocation, and audit trails without affecting
other sessions.

Key design decisions:

1. **Token Hash Storage:** Only SHA-256 hash of token is stored (never raw token).
   If database is breached, attacker does not get usable tokens (they'd need to
   reverse-engineer SHA-256, which is cryptographically infeasible). Raw token
   transmitted only during issuance to client over HTTPS.

2. **Server-Side Revocation:** Refresh token is the control point for session
   management. Unlike stateless JWT access tokens, refresh tokens can be revoked
   at any time: logout, password change, device lock, admin session termination,
   or suspicious activity detection.

3. **Per-Device Sessions:** Each device has its own refresh token record. User can
   log out from one device without affecting login on another. User agent + IP
   address provides audit context for "which device is this?"

4. **Cascade Deletion:** Foreign key ON DELETE CASCADE ensures tokens are hard-deleted
   when user is deleted (not just orphaned). Simplifies data retention and prevents
   querying tokens for deleted users.

5. **Immutable Token Hash:** token_hash is set on creation and never modified.
   Prevents accidental corruption of the security mechanism.

6. **Explicit Revocation Timestamp:** revoked_at is null for active tokens,
   set to current timestamp when revoked. Enables querying: "When was this token
   revoked?" and "Has this token been revoked since time T?"

7. **Expiry Timestamp:** expires_at is absolute UTC timestamp (not relative TTL).
   Simplifies comparison logic (expires_at > now()) and enables partial index
   (on expired tokens) for efficient cleanup queries.

Lifecycle:

1. **Issuance:** User logs in successfully. Application generates random token,
   hashes it, creates RefreshToken record with expires_at and user context.
   Raw token returned to client (over HTTPS only).

2. **Storage:** Client stores token securely (HttpOnly cookie or secure storage).

3. **Refresh:** Client sends refresh token with next request. Application looks up
   token by hash, validates expiry and revocation status. If valid, issues new
   access token and new refresh token (rotation pattern).

4. **Revocation:** User logs out, changes password, or admin revokes session.
   Application sets is_revoked=True and revoked_at=now(). Token cannot be used
   again.

5. **Cleanup:** Background job queries (expires_at < now() AND is_revoked=false)
   and hard-deletes expired tokens. Partial index makes this efficient.

6. **Deletion:** User deleted. ON DELETE CASCADE removes all refresh tokens for
   that user.

Database Constraints:

- **Primary Key:** id (UUID, auto-generated, immutable)
- **Foreign Key:** user_id → users.id (ON DELETE CASCADE)
- **Unique Constraint:** token_hash (prevents duplicate hashes)
- **NOT NULL Constraints:** user_id, token_hash, expires_at, is_revoked, created_at
- **Nullable Fields:** user_agent, ip_address, revoked_at

Indexes:

- **Primary Index:** id (automatic from primary key)
- **Unique Index:** token_hash (fast validation lookup, automatic from unique=True)
- **User Index:** user_id (session listing for a user: "All tokens for user X")
- **Partial Index:** (expires_at) WHERE is_revoked=False (efficient cleanup queries)

Security Notes:

- token_hash is NEVER logged or exposed in API responses (repository layer)
- Token secret is generated by application and transmitted only via HTTPS
- IP address and user agent provide context but are not security mechanisms
  (can be spoofed; used for monitoring and audit trails only)
- Revocation is immediate: setting is_revoked=True takes effect on next API request
- No rate limiting in this model; application layer enforces limits

Security Traces:
- 08-Security-Architecture §5: JWT and refresh token lifecycle
- 08-Security-Architecture §6: Audit trail integrity
- 02-Domain-Model §2: Observability as cross-cutting concern

Traces to: 04-Database-Design §4 (ERD), user_refresh_tokens table specification
Traces to: 04-Database-Design §3.2 (Refresh tokens as server-side session control)
Traces to: 04-Database-Design §5.2 (RefreshToken schema specification)
Traces to: 08-Security-Architecture §5 (JWT and refresh token lifecycle)
Traces to: 07-Backend-Development-Standards §8 (ORM model conventions)
Traces to: 22-Engineering-Backlog E3.T9 (Refresh Tokens ORM Model and Migration task)
"""

from __future__ import annotations

from datetime import datetime  # noqa: TC003
from uuid import UUID  # noqa: TC003

from sqlalchemy import ForeignKey, Index, String
from sqlalchemy.dialects.postgresql import INET, TIMESTAMP
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.infrastructure.database.base import BaseModel


class RefreshToken(BaseModel):
    """
    RefreshToken entity for server-side session management.

    Inherits from BaseModel:
        - id: UUID primary key (automatically generated, immutable)
        - created_at: Timestamp of token issuance (immutable)
        - updated_at: Timestamp of last modification (updated on revocation)
        - deleted_at: Soft-delete timestamp (nullable, unused for refresh tokens)

    This model stores the server-side state of refresh tokens. Each token record
    represents one active or revoked session for a user. The token is never stored
    in plaintext; only the SHA-256 hash is persisted.

    Lifecycle:

        1. **Issuance:** User authenticates successfully. Application generates
           random token, hashes it with SHA-256, creates RefreshToken record
           with expiry time and session context (user-agent, IP). Raw token
           returned to client.

        2. **Storage:** Client stores token (HttpOnly cookie or secure storage).

        3. **Refresh:** Client sends token. Application hashes it, looks up record
           by hash, validates expiry/revocation. If valid, issues new access token
           and new refresh token (rotation).

        4. **Revocation:** User logs out, changes password, or admin revokes.
           Application sets is_revoked=true and revoked_at=now(). Token cannot
           be used again.

        5. **Cleanup:** Background job queries (expires_at < now() AND
           is_revoked=false) and hard-deletes expired, non-revoked tokens.

        6. **Deletion:** User deleted. ON DELETE CASCADE removes all their tokens.

    Token Hash Security:

        The token_hash field stores the output of SHA-256 applied to the opaque
        token value. SHA-256 is cryptographically secure (one-way, collision-
        resistant). If the database is breached:

        - Attacker sees hashes, not plaintext tokens
        - Attacker cannot reverse SHA-256 to recover tokens
        - Active sessions remain secure
        - Attacker gains no value from hashes alone

        This is the same approach used by major identity providers (Google, Auth0,
        AWS Cognito). The raw token is transmitted only over HTTPS during issuance
        and refresh flows.

    Revocation vs. Expiry:

        - **Expiry:** Automatic, timestamp-based. Token becomes unusable at
          expires_at time regardless of is_revoked flag. Used for normal token
          lifecycle (e.g., 30 days of inactivity).

        - **Revocation:** Explicit, event-based. Admin or user action sets
          is_revoked=true, making token unusable immediately. Used for logout,
          password reset, security incidents.

    Query Patterns:

        ```python
        # Validate token (is it usable?)
        SELECT * FROM user_refresh_tokens
        WHERE token_hash = %s
        AND is_revoked = false
        AND expires_at > now()
        LIMIT 1

        # List sessions for user
        SELECT * FROM user_refresh_tokens
        WHERE user_id = %s
        AND is_revoked = false
        AND expires_at > now()
        ORDER BY created_at DESC

        # Cleanup expired tokens
        SELECT * FROM user_refresh_tokens
        WHERE is_revoked = false
        AND expires_at < now()
        # Then DELETE (scheduled background job)

        # Revoke all user sessions (password change)
        UPDATE user_refresh_tokens
        SET is_revoked = true, revoked_at = now(), updated_at = now()
        WHERE user_id = %s
        AND is_revoked = false
        ```

    Indexes:

        - **token_hash (unique):** Fast O(1) validation lookup
        - **user_id:** Fast session listing ("All tokens for this user?")
        - **(expires_at) partial WHERE is_revoked=false:** Fast cleanup queries

    Example Usage:

        ```python
        from app.models.refresh_token import RefreshToken
        from datetime import datetime, timedelta, UTC
        from secrets import token_urlsafe
        import hashlib

        # Generate token (application layer)
        raw_token = token_urlsafe(48)
        token_hash = hashlib.sha256(raw_token.encode()).hexdigest()

        # Create record
        refresh_token = RefreshToken(
            user_id=user_id,
            token_hash=token_hash,
            expires_at=datetime.now(UTC) + timedelta(days=30),
            user_agent=request.headers.get("user-agent"),
            ip_address=request.client.host,
        )
        session.add(refresh_token)
        await session.commit()

        # Later: validate token
        token_hash = hashlib.sha256(raw_token.encode()).hexdigest()
        record = await session.execute(
            select(RefreshToken)
            .where(
                RefreshToken.token_hash == token_hash,
                RefreshToken.is_revoked == False,
                RefreshToken.expires_at > datetime.now(UTC),
            )
        )
        ```

    Relationships:

        - **User:** Foreign key to users.id. ON DELETE CASCADE ensures tokens are
          deleted when user is deleted. Unidirectional (no back_populates on User
          in this version; can be added if User.refresh_tokens collection is needed).

    Constraints:

        - **Unique:** token_hash (prevents duplicate hashes in database)
        - **Primary Key:** id (automatic)
        - **Foreign Key:** user_id → users.id (ON DELETE CASCADE)
        - **NOT NULL:** user_id, token_hash, expires_at, is_revoked, created_at
        - **Nullable:** user_agent, ip_address, revoked_at

    Traces to: 04-Database-Design §5.2 (RefreshToken schema)
    Traces to: 08-Security-Architecture §5 (token lifecycle)
    Traces to: backend/openapi.yaml RefreshToken schema
    """

    __tablename__ = "user_refresh_tokens"

    # User ID - Foreign key to users table
    # NOT nullable (every token belongs to a user)
    # ON DELETE CASCADE: deleting user deletes all their tokens
    # Indexed for efficient session listing queries
    user_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="FK to users table; ON DELETE CASCADE",
    )

    # JWT ID (jti) - Unique identifier from JWT payload for revocation tracking
    # UNIQUE constraint: ensures each token has unique jti
    # Indexed for efficient lookup during token validation
    # NOT nullable (required for revocation tracking)
    jti: Mapped[str] = mapped_column(
        String(256),  # JWT IDs are typically UUIDs or base64-encoded values
        unique=True,
        nullable=False,
        index=True,
        comment="JWT ID from token payload; unique constraint for revocation",
    )

    # Token Hash - SHA-256 hash of the opaque token value
    # NEVER the raw token (security: hash, never plaintext)
    # UNIQUE constraint: prevents duplicate hashes in database
    # Indexed for O(1) validation lookup
    # NOT nullable (required for validation)
    # NOT exposed in __repr__() for security
    token_hash: Mapped[str] = mapped_column(
        String(64),  # SHA-256 produces 64 hex characters (32 bytes)
        unique=True,
        nullable=False,
        index=True,
        comment="SHA-256 hash of token value (not raw token); unique constraint",
    )

    # Expiry Timestamp - When token becomes invalid due to age
    # Absolute UTC timestamp (not relative TTL)
    # NOT nullable (every token has an expiry)
    # Used for: expires_at > now() validation
    # Indexed (partial) for efficient cleanup of expired tokens
    expires_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        comment="Absolute UTC timestamp; token invalid after this time",
    )

    # Revocation Flag - Whether token has been explicitly revoked
    # Default: False (token starts active)
    # True: token cannot be used, regardless of expiry
    # Set by: logout, password change, admin revocation, security incident
    # Used for: explicit session termination without waiting for expiry
    is_revoked: Mapped[bool] = mapped_column(
        nullable=False,
        server_default="false",
        default=False,
        comment="Explicit revocation flag; false=active, true=revoked",
    )

    # User Agent - HTTP User-Agent header from client
    # Nullable (some clients may not send)
    # Used for: audit trail, session context ("which device?")
    # NOT a security mechanism (can be spoofed)
    # Examples: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)...",
    #          "curl/7.68.0"
    user_agent: Mapped[str | None] = mapped_column(
        String(512),  # Typical user agents are 100-200 chars; allow headroom
        nullable=True,
        comment="HTTP User-Agent header; context for audit trail",
    )

    # IP Address - Client IP address (X-Forwarded-For or request.remote_addr)
    # Nullable (some clients may not have visible IP)
    # Stored as INET type (PostgreSQL native IP address type)
    # Used for: audit trail, geographic tracking, abuse detection
    # NOT a security mechanism (can be spoofed; VPNs, proxies)
    # Examples: "192.0.2.1", "2001:db8::1"
    ip_address: Mapped[str | None] = mapped_column(
        INET(),
        nullable=True,
        comment="Client IP address (X-Forwarded-For or remote_addr); audit context",
    )

    # Revocation Timestamp - When token was explicitly revoked
    # Null for active tokens (is_revoked=False)
    # Set to now() when token is revoked (is_revoked becomes True)
    # Used for: "when was this token revoked?", compliance reports
    revoked_at: Mapped[datetime | None] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=True,
        comment="UTC timestamp when token was revoked; null for active tokens",
    )

    # Table-level constraints and indexes
    __table_args__ = (
        # Index on user_id for efficient session listing
        # Query: "Get all tokens for this user" (to revoke all on password change)
        Index(
            "ix_user_refresh_tokens_user_id",
            "user_id",
        ),
        # Partial index on (expires_at) for efficient cleanup of expired tokens
        # Query: "Find all expired, non-revoked tokens to delete"
        # Condition: is_revoked=false (don't waste space on already-revoked tokens)
        # PostgreSQL syntax: CREATE INDEX ... WHERE is_revoked = false
        Index(
            "ix_user_refresh_tokens_expires_at_active",
            "expires_at",
            postgresql_where=("is_revoked = false"),
        ),
    )

    def __repr__(self) -> str:
        """
        String representation for debugging.

        Does NOT include token_hash for security (hashes are sensitive).

        Returns:
            String like '<RefreshToken id=uuid user_id=uuid revoked=false>'

        Security Note:
            Never log the token_hash. Even though it's a hash (not plaintext),
            exposing hashes could aid attackers in precomputation attacks or
            finding collisions. Keep hashes secret.
        """
        return (
            f"<RefreshToken id={self.id} user_id={self.user_id} "
            f"revoked={self.is_revoked} expires_at={self.expires_at}>"
        )
