"""
Report ORM model.

Defines the report entity representing an analysis report generated by the system.
A report summarizes the analysis of a digital asset and contains findings,
verdicts, and recommendations.

Key design decisions:

1. **Immutability after creation:** Report is primarily immutable. Core fields
   (asset_id, analysis_id, title, content) are set at creation and do not change.
   Status transitions are allowed but status is the only field that should change
   after creation.

2. **Status field:** Tracks report lifecycle (draft, published, archived).
   Stored as VARCHAR with CHECK constraint (not PostgreSQL ENUM) to enable
   zero-downtime status additions.

3. **Optional analysis_id:** A report may be standalone (user-created) without
   an associated analysis. analysis_id is nullable.

4. **Foreign keys:** asset_id points to DigitalAsset (required), analysis_id
   points to Analysis (optional). created_by points to User (required).

5. **Soft delete:** deleted_at timestamp for soft deletion. Preserves audit trail
   and enables recovery if needed.

6. **Inheritance from BaseModel:** Brings UUID PK, created_at, updated_at,
   deleted_at audit fields. Consistency with other models.

7. **Indexes:** Optimize common queries:
   - (asset_id, created_at DESC): Reports for a specific asset
   - (status, created_at DESC): Filter by status
   - (created_by, created_at DESC): Reports created by a specific user

Security notes:
- Every report is created by a user (created_by FK enforced)
- Reports are associated with a digital asset (asset_id FK enforced)
- Soft delete preserves audit trail
- Status field controls visibility and report state

Lifecycle:
1. Created: Report created by user, initially draft status
2. Published: Report published, visible to stakeholders
3. Archived: Report archived, hidden from active queries
4. Soft-deleted: Report deleted, excluded from queries, data preserved for audit

Traces to: 04-Database-Design §4 (ERD), §5.7 (Report table spec)
Traces to: 22-Engineering-Backlog E3.T7 (Report ORM model task)
"""

from __future__ import annotations

import enum
from datetime import datetime  # noqa: TC003
from uuid import UUID  # noqa: TC003

from sqlalchemy import CheckConstraint, ForeignKey, Index, String
from sqlalchemy.dialects.postgresql import TIMESTAMP
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.infrastructure.database.base import BaseModel


class ReportStatus(enum.StrEnum):
    """
    Report status enumeration.

    Tracks the lifecycle state of a report from creation through publication
    and archival.

    Stored as VARCHAR with CHECK constraint (not PostgreSQL ENUM) to enable
    zero-downtime status additions.
    """

    DRAFT = "draft"
    """Report is being prepared, not yet published."""

    PUBLISHED = "published"
    """Report is finalized and published for stakeholders."""

    ARCHIVED = "archived"
    """Report is archived and hidden from active queries."""


class Report(BaseModel):
    """
    Report entity representing an analysis report for a digital asset.

    Inherits from BaseModel:
        - id: UUID primary key (automatically generated)
        - created_at: Timestamp of report creation (immutable)
        - updated_at: Timestamp of last modification (auto-updated)

    Reports summarize the analysis of a digital asset and contain findings,
    verdicts, and recommendations. A report is always associated with a
    DigitalAsset and optionally with a specific Analysis.

    Lifecycle states:
        1. Draft: Report is being prepared
        2. Published: Report is finalized and shared
        3. Archived: Report is archived, hidden from active queries
        4. Soft-deleted: deleted_at set, excluded from queries, data preserved

    Example:
        >>> from app.models.report import Report, ReportStatus
        >>> report = Report(
        ...     asset_id=asset_uuid,
        ...     created_by=user_uuid,
        ...     title="Security Analysis Report",
        ...     status=ReportStatus.DRAFT,
        ... )
        >>> session.add(report)
        >>> await session.commit()

    Relationships:
        - asset: DigitalAsset entity (FK to digital_assets.id)
        - analysis: Analysis entity (optional, FK to analyses.id)
        - creator: User entity (FK to users.id)

    Traces to: 04-Database-Design §5.7 (Report table spec)
    Traces to: backend/openapi.yaml Report schema
    """

    __tablename__ = "reports"

    # Asset relationship - required, every report is for an asset
    asset: Mapped[DigitalAsset] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "DigitalAsset",
        lazy="selectin",
    )

    # Analysis relationship - optional
    analysis: Mapped[Analysis | None] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "Analysis",
        lazy="selectin",
    )

    # Creator relationship - required, every report is created by a user
    creator: Mapped[User] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "User",
        lazy="selectin",
    )

    # Asset ID - Foreign key to digital_assets table
    # Required: every report must be associated with an asset
    asset_id: Mapped[UUID] = mapped_column(
        ForeignKey("digital_assets.id"),
        nullable=False,
        comment="FK to digital_assets.id, required",
    )

    # Analysis ID - Foreign key to analyses table
    # Optional: a report may not have an associated analysis
    analysis_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("analyses.id"),
        nullable=True,
        comment="FK to analyses.id, optional",
    )

    # Title - Short description of the report
    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Report title, displayed in UI",
    )

    # Description - Longer description or summary
    description: Mapped[str | None] = mapped_column(
        String(1000),
        nullable=True,
        comment="Optional description or summary",
    )

    # Status - Current state of the report
    # Stored as VARCHAR with CHECK constraint to enable zero-downtime additions
    status: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default=ReportStatus.DRAFT.value,
        server_default=f"'{ReportStatus.DRAFT.value}'",
        comment="Report status: draft, published, archived",
    )

    # Content - The actual report content (markdown, HTML, etc.)
    content: Mapped[str | None] = mapped_column(
        nullable=True,
        comment="Report body/content",
    )

    # Created by - User who created the report
    created_by: Mapped[UUID] = mapped_column(
        ForeignKey("users.id"),
        nullable=False,
        comment="FK to users.id, user who created the report",
    )

    # Soft delete timestamp
    deleted_at: Mapped[datetime | None] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=True,
        comment="Soft delete timestamp (UTC), null = active",
    )

    # Table-level constraints
    __table_args__ = (
        # Enforce status values at database level
        CheckConstraint(
            (
                f"status IN ('{ReportStatus.DRAFT.value}', "
                f"'{ReportStatus.PUBLISHED.value}', "
                f"'{ReportStatus.ARCHIVED.value}')"
            ),
            name="ck_reports_status_valid",
        ),
        # Index for asset-specific report queries
        Index(
            "ix_reports_asset_created",
            "asset_id",
            "created_at",
            postgresql_ops={"created_at": "DESC"},
        ),
        # Index for status-based queries
        Index(
            "ix_reports_status_created",
            "status",
            "created_at",
            postgresql_ops={"created_at": "DESC"},
        ),
        # Index for user-specific report queries
        Index(
            "ix_reports_created_by",
            "created_by",
            "created_at",
            postgresql_ops={"created_at": "DESC"},
        ),
        # Index for soft-delete queries
        Index(
            "ix_reports_deleted_at",
            "deleted_at",
        ),
    )

    def __repr__(self) -> str:
        """
        String representation for debugging.

        Returns:
            String like '<Report id=uuid asset_id=uuid status=draft>'
        """
        return (
            f"<Report id={self.id} asset_id={self.asset_id} "
            f"status={self.status}>"
        )
