"""AuditLog domain entity.

Represents an immutable audit trail record for all state-changing operations
in the Sentinel system. This is a domain model (business logic), not an ORM
model. It contains no SQLAlchemy imports or database-specific code.

Per design.md § Audit Logging (Requirement 8):
- Audit logs are append-only (immutable)
- No update() or delete() operations allowed
- Captures who, what, when, where, whether operation succeeded
- State snapshots (before/after) enable forensic analysis
- Timestamps use server time (never client-supplied)

Traces to: 08-Security-Architecture §6 (audit trail integrity)
Traces to: 04-Database-Design §11 (audit strategy)
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from datetime import datetime
    from uuid import UUID


@dataclass
class AuditLog:
    """
    Immutable audit trail record for state-changing operations.

    Invariants:
    - id is immutable UUID (set at creation)
    - Once created, audit log cannot be modified or deleted
    - Timestamps use server time (never client-supplied)
    - actor_id may be None for system-initiated operations
    - before_state and after_state are full entity snapshots (JSONB)
    - Application layer sanitizes state (strips passwords, tokens, PII)

    Attributes:
        actor_id: User who performed the action (nullable for system operations)
        actor_role: Role of actor at time of action (snapshot)
        action: Operation type (e.g., "USER_LOGIN", "ROLE_CHANGE")
        resource_type: Entity type affected (e.g., "User", "DigitalAsset")
        resource_id: ID of affected entity
        before_state: Full entity snapshot before operation (nullable for creates)
        after_state: Full entity snapshot after operation (nullable for deletes)
        ip_address: Client IP address (from X-Forwarded-For or request)
        request_id: Correlation ID for distributed tracing
        user_agent: HTTP User-Agent header for context
        success: Whether operation succeeded
        failure_reason: Error message if success=False
        occurred_at: Server timestamp of operation (UTC)
        id: Unique identifier (immutable, generated by repository)
        created_at: Timestamp of audit record creation (generated by repository)
    """

    actor_id: UUID | None  # Nullable for system operations
    actor_role: str  # Snapshot of role at action time
    action: str  # Operation type
    resource_type: str  # Entity type affected
    resource_id: UUID  # ID of affected entity
    before_state: dict[str, object] | None  # Full entity snapshot before
    after_state: dict[str, object] | None  # Full entity snapshot after
    ip_address: str | None  # Client IP
    request_id: str | None  # Correlation ID
    user_agent: str | None  # Client User-Agent
    success: bool  # Operation success flag
    failure_reason: str | None  # Error message if failed
    occurred_at: datetime  # Server timestamp (UTC)
    id: UUID | None = None  # Set by repository on create
    created_at: datetime | None = None  # Set by repository on create

    def __post_init__(self) -> None:
        """Validate immutability invariants."""
        # Audit logs are immutable: no modifications allowed after creation
        # This is semantic enforcement; database layer enforces with GRANT rules
        pass
