"""
Report domain entity.

Represents an analysis report generated by the system. This is a domain model
(business logic), not an ORM model. It contains no SQLAlchemy imports or
database-specific code.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from datetime import datetime
    from uuid import UUID


@dataclass
class Report:
    """Report domain entity."""

    id: UUID
    asset_id: UUID
    analysis_id: UUID | None
    title: str
    description: str | None
    status: str
    content: str | None
    created_by: UUID
    created_at: datetime
    updated_at: datetime
    deleted_at: datetime | None = None
