"""
Alembic migration environment configuration.

This module is executed by Alembic when running migrations. It connects
Alembic to the application's database settings and SQLAlchemy metadata,
enabling autogeneration of migration scripts from ORM model changes.

Key responsibilities:
- Import Base.metadata for autogenerate support
- Source DATABASE_MIGRATION_URL from environment variables
- Configure migration context (online/offline modes)
- Handle async SQLAlchemy engine if needed

Traces to: 07-Backend-Development-Standards §8 (migrations)
Traces to: 22-Engineering-Backlog E3.T2 (Alembic configuration)
"""

import os
from logging.config import fileConfig

from dotenv import load_dotenv
from alembic import context
from sqlalchemy import engine_from_config, pool


# Load environment variables from .env file
load_dotenv()


# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Import Base.metadata for autogenerate support.
# Alembic inspects this metadata to detect model changes and generate
# migration scripts automatically.
#
# IMPORTANT: All ORM models must be imported before this metadata is used.
# If a model is not imported, its table will not appear in autogenerated
# migrations. Import models here or ensure they're imported in base.py.
from app.infrastructure.database.base import Base  # noqa: E402
import app.models  # noqa: E402, F401


target_metadata = Base.metadata

# Source DATABASE_MIGRATION_URL from environment.
# This overrides the placeholder in alembic.ini, ensuring migrations use
# the correct database connection without hardcoded credentials.
#
# DATABASE_MIGRATION_URL should have DDL privileges (CREATE TABLE, ALTER TABLE)
# while DATABASE_URL (used by the application) may have restricted privileges
# (SELECT, INSERT, UPDATE, DELETE only).
#
# Traces to: 08-Security-Architecture §9 (least privilege)
database_url = os.environ.get("DATABASE_MIGRATION_URL")
if database_url:
    config.set_main_option("sqlalchemy.url", database_url)


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        # Include naming convention for constraint generation
        render_as_batch=False,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    # Get the configured URL (which was set from DATABASE_MIGRATION_URL)
    url = config.get_main_option("sqlalchemy.url")
    
    # Convert postgresql+asyncpg:// to postgresql:// for Alembic.
    # Alembic doesn't support async drivers, so we use the sync psycopg2 driver
    # for migrations only. The application uses asyncpg for async operations.
    if url and "postgresql+asyncpg://" in url:
        url = url.replace("postgresql+asyncpg://", "postgresql://")
        config.set_main_option("sqlalchemy.url", url)
    
    alembic_config = config.get_section(config.config_ini_section, {})

    connectable = engine_from_config(
        alembic_config,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
