"""
Dependency injection helpers for FastAPI.

Provides dependency-injection callables for use with FastAPI's Depends()
mechanism. Implements the DI foundation with singleton (settings) and
request-scoped (logging, context) providers.

The infrastructure is modular and composable, prepared for future
infrastructure providers (database, Redis, storage, AI clients) which
will be added in later Epics.

Core Providers:
  - get_settings(): Singleton Settings instance (cached via @lru_cache)
  - get_logger(name): Named loggers with request context via contextvars
  - get_request_context(): Request-scoped context with request_id
  - get_db_session(): Request-scoped database session (from infrastructure)

See: 07-Backend-Development-Standards §3 (dependency injection).
See: 06-Repository-Structure §3 (app/core/dependencies).
See: 10-Observability-Architecture §2 (request context propagation).
See: 22-Engineering-Backlog E3.T1 (database dependency export).
"""

import logging
from contextvars import ContextVar
from functools import lru_cache
from typing import Any

from fastapi import Request

from app.core.settings import Settings
from app.infrastructure.database.session import get_db_session


# Re-exports for DI interface
__all__ = [
    "RequestContext",
    "get_db_session",
    "get_logger",
    "get_request_context",
    "get_request_context_dict",
    "get_settings",
]


# ===========================================================================
# Context Variables
# ===========================================================================
# Async-safe, thread-local storage for request-scoped data.
# These propagate across async boundaries (unlike thread-local storage).
#
# See: 10-Observability-Architecture §2 (context propagation).
# ===========================================================================

_request_context_var: ContextVar[dict[str, Any] | None] = ContextVar(
    "request_context",
    default=None,
)


# ===========================================================================
# Settings Provider
# ===========================================================================


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Get the cached, singleton Settings instance.

    Uses @lru_cache to load and validate configuration exactly once
    at first call, then return the same instance on subsequent calls.
    This is more efficient than reloading from environment on every request.

    Raises:
        ValidationError: If any required environment variable is missing
            or any configuration value is invalid. The application will
            not start if configuration is incomplete.

    Returns:
        Settings: Validated, immutable configuration object.

    Example:
        @router.get("/health")
        async def health(settings: Settings = Depends(get_settings)) -> dict[str, str]:
            return {"status": "ok", "app": settings.name}

    See: 07-Backend-Development-Standards §2 (fail fast on invalid config).
    """
    return Settings()


# ===========================================================================
# Logging Provider
# ===========================================================================


def get_logger(name: str) -> logging.Logger:
    """Get a named logger with request context support.

    Returns a standard Python logger configured with the logging settings
    from Settings. The logger automatically propagates request_id and
    correlation data through contextvars for structured logging.

    Args:
        name: Logger name (typically __name__ or a module path).

    Returns:
        logging.Logger: Configured logger with request context support.

    Example:
        logger = get_logger(__name__)
        logger.info("Processing upload", extra={"file_id": file_id})

    See: 07-Backend-Development-Standards §10 (structured logging).
    See: 10-Observability-Architecture §4 (context propagation).
    """
    logger = logging.getLogger(name)

    # Logger is configured during application startup by the
    # LoggingInitializer (if implemented in E1.T7).
    # This function ensures consistent logger acquisition.
    return logger


# ===========================================================================
# Request Context Provider
# ===========================================================================


class RequestContext:
    """Request-scoped context for correlation and tracking.

    Encapsulates request metadata that should be available to all
    downstream code (routes, services, repositories). This provides
    the foundation for:
    - Request ID correlation (X-Request-ID header)
    - Distributed tracing
    - Audit logging
    - Structured logging

    Attributes:
        request_id: Unique ID for this request (from X-Request-ID header
            or generated by RequestIdMiddleware).
        correlation_id: Optional external correlation ID from client.
        user_id: Optional authenticated user ID (populated by auth layer).

    See: 10-Observability-Architecture §2 (request context).
    See: 08-Security-Architecture §10 (audit tracking).
    """

    def __init__(self, request_id: str, correlation_id: str | None = None) -> None:
        """Initialize request context with correlation IDs.

        Args:
            request_id: Request ID from X-Request-ID header or generated.
            correlation_id: Optional external correlation ID for tracing.
        """
        self.request_id = request_id
        self.correlation_id = correlation_id or request_id
        self.user_id: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert context to dictionary for logging/tracing.

        Returns:
            Dictionary with request_id, correlation_id, and user_id.
        """
        return {
            "request_id": self.request_id,
            "correlation_id": self.correlation_id,
            "user_id": self.user_id,
        }


async def get_request_context(request: Request) -> RequestContext:
    """Get or create request-scoped context.

    Extracts the request_id from middleware (stored in request.state),
    creates a RequestContext instance, and stores it in contextvars
    for access by downstream code without explicit parameter passing.

    Args:
        request: FastAPI request object (injected by framework).

    Returns:
        RequestContext: Request-scoped context instance.

    Raises:
        ValueError: If request_id is not present in request.state.
            This indicates RequestIdMiddleware was not registered.

    Example:
        @router.get("/uploads")
        async def list_uploads(
            ctx: RequestContext = Depends(get_request_context),
        ) -> list[UploadDto]:
            logger.info("Listing uploads", extra=ctx.to_dict())
            return await upload_service.list_uploads()

    See: 10-Observability-Architecture §2 (request context propagation).
    """
    request_id = getattr(request.state, "request_id", None)

    if not request_id:
        raise ValueError(
            "request_id not found in request.state. "
            "RequestIdMiddleware must be registered."
        )

    # Extract correlation ID from header if provided
    correlation_id = request.headers.get("X-Correlation-ID")

    # Create context instance
    context = RequestContext(
        request_id=request_id,
        correlation_id=correlation_id,
    )

    # Store in contextvar for access by downstream code
    _request_context_var.set(context.to_dict())

    return context


def get_request_context_dict() -> dict[str, Any]:
    """Get the current request context as a dictionary.

    This is a helper for logging and tracing that doesn't require
    the Request object (useful in services, repositories, etc.).

    Returns:
        Dictionary with request context data, or empty dict if no context.

    Example:
        # In a service class, without route handler context
        ctx = get_request_context_dict()
        logger.info("Processing", extra=ctx)

    See: 10-Observability-Architecture §2 (context propagation).
    """
    context = _request_context_var.get()
    return context if context is not None else {}
